scientific-python/pytest-doctestplus

CHANGES.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py
This add two configuration options: `doctest_plus_atol` and `doctest_plus_rtol`. For example, the following configuration would result in the current default comparison:
```
[tool:pytest]
doctest_plus_atol = 1e-08
doctest_plus_rtol = 1e-05
```
Some numerical packages cannot reach the numpy default precision and default object representation (e.g., pandas) prints truncated floating number.
=> Tolerance option

CHANGES.rst, README.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
Fixes #10 
This extends #39 so that it is possible to set `FLOAT_CMP` globally in `setup.cfg`/`pytest.ini`.
=> Add option for global FLOAT_CMP in setup.cfg

.travis.yml, CHANGES.rst, appveyor.yml, pytest_doctestplus/plugin.py, tests/docs/skip_all.tex, tests/docs/skip_some.tex
This should fix #42 
The system is now flexible so can be extend with other text file extensions and comment characters.
=> Make doctestplus work for TeX

pytest_doctestplus/plugin.py
This is a follow-up for #43 as with that one I run into a few corner cases.
- now possible to set the format in `pytest.ini` only (previously the comment string wasn't picked up correctly for that case)
- now the comment character defaults to the one for `rst` format, so when a non mapped format is specified the test is not failing with undefined variable, but runs the doctest with a warning.
- this PR not makes it possible to override the `pytest.ini` value for the format on the command line
Missing feature, but it's beyond this PR is to make it possible to make the formats and comment characters configurable.
(also, it seems that `config.getoptio()` is not working as expected, at least it didn't picked up the default specified rather it defaulted to None)
=> Fixing precedent and few corner cases

tests/test_doctestplus.py
This came to light in https://github.com/astropy/astropy/pull/8495. This problem has probably existed for a long time, but now that it is possible to set both `FLOAT_CMP` and `ELLIPSIS` as global settings (thanks to #40), it is now evident in certain test cases.
=> Add (xfail) test showing incompatibility between FLOAT_CMP and ELLIPSIS

pytest_doctestplus/plugin.py
I've noticed this `SyntaxWarning` in an output done with Python 3.9 (see [here](https://gist.github.com/cdeil/9586f0c3666d1afe3132a290ce92fc5f)).
=> Avoid SyntaxWarning regarding invalid escape sequence in newer Python versions

.travis.yml, pytest_doctestplus/plugin.py, setup.cfg
See https://github.com/pytest-dev/pytest/releases/tag/5.1.0 . This is to fix:
```
E   AttributeError: 'FixtureRequest' object has no attribute 'getfuncargvalue'
```
Example log: https://circleci.com/gh/astropy/astropy/40431
p.s. How far back do we need to be backward compatible? Or is a simple renaming like this okay?
xref pytest-dev/pytest#2682
=> Compatibility with pytest 5.1

pytest_doctestplus/plugin.py
Ugly but works, and frankly I can't wait to remove the python2 support anyway.
Before this PR I see:
```
/usr/local/lib/python3.7/site-packages/pytest_doctestplus/plugin.py:10: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
=> Avoid the imp deprecation warning, yet keep python2 support

pytest_doctestplus/output_checker.py, setup.py
Using this with sympy pulled in numpy as a dependency. It seems unnecessary to have such a big dependency just for `allclose`. This patch eliminates that dependency by reimplementing allclose for scalars.
The implementation is based on the [documented formula for allclose](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.allclose.html)
=> Inline np.allclose to remove dependency on numpy

README.rst
Since the Python documentation for `doctest` is quite incomplete, it would be nice to have some examples here on usage.
=> Add doctest skip examples to README.rst

pytest_doctestplus/plugin.py, pytest_doctestplus/utils.py, tests/docs/skip_some.rst, tests/test_doctestplus.py, tests/test_utils.py
close #57
close #29
close #18
Old regex `\s*,?\s*` used in re.split produces `['s', 'y', 's']` from string `'sys'`.
New regex `\s*[,\s]\s*`:
'sys' -> ['sys']
'sys pandas' -> ['sys', 'pandas']
'sys, pandas<=123' -> ['sys', 'pandas<=123']
'sys,pandas' -> ['sys', 'pandas']
'sys , pandas' -> ['sys', 'pandas']
For python3.4+ there is `pkg_resources.require` to check that package with specified version is available. 
For python2 (which should be already dropped) I wrote custom version checker which essentially just pull packages info from `pip freeze` output and compare versions using `distutils.version.LooseVersion`.
`pip freeze`  is triggered only for python3.4-.
=> allow to specify module version doctest-requires sphinx directive

README.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
There are cases where lines in a doctest will emit a warning but we don't necessarily want to show it in the output or have the warning end up being counted by pytest. This new directive will make sure all warnings on that line will be silenced.
@vanyakosmos - feel free to review this if you'd like, since you are very familiar with this plugin! :)
@pllim - you might also be interested in this :)
=> New directive +IGNORE_WARNINGS to capture and silence warnings

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
close #9 
close #48
I marked `text-file-format` and `doctest-rst` as deprecated. But right now `doctest-glob` list is extended with `"*.{text_file_format}"` if `doctest_rst` is `True`. So `text-file-format` and `doctest-rst` will still work as expected.
Also comment chars are now determined by file extension instead of `text_file_format` and can be configured via ini variable `text_file_comment_chars`
```
[pytest]
text_file_comment_chars = 
.rst=#
.tex=#
```
default ones are still:
```
comment_characters = {
'.txt': '#',
'.tex': '%',
'.rst': '..'
}
```
=> use doctest-glob instead of doctest-rst and text-file-format

CHANGES.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, tests/conftest.py, tests/test_doctestplus.py
close #14
`--doctest-only` will implicitly use doctest-plus and will filter out all python test files (`python_files` in `pytest.ini`, eg `test_*.py`).
check out `test_doctest_only` for usage details https://github.com/astropy/pytest-doctestplus/blob/b1da7f4d0b4f4b6e2dc3423f42f715732a4cca80/tests/test_doctestplus.py#L395-L416
=> add doctest-only option

setup.py
Is this what you had in mind @olebole for #89?
(I haven't found a precedent for it in any of the packages I looked into. The closest was  setuptools, but even there pip and wheel is just an optional dependency and thus not listed in the setup files).
=> Adding pip as dependency

.travis.yml
~For some reason, `pytest` 5.0 is being picked up, not 5.4.x, so this PR pins it to 5.4.1. This is not ideal as someone needs to remember to bump it time and again. This is not needed if a fix can be made upstream at `ci-helpers`.~ (Turns out `ci-helpers` picking up 5.3 from `conda` and only falls back to PyPI when `conda` fails.)
**EDIT:** Now only bumps accompanying Python to 3.8. (Why not?)
=> TST: Bump latest Python version to 3.8

.travis.yml, CHANGES.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, setup.py, tests/test_doctestplus.py
This is quite similar to #95, but I started from scratch and porting some code from pytest's doctest plugin which probably changed a lot since the first version of doctestplus.
With these changes I had a few tests failing, and I actually don't understand why the tests were not failing before so I updated the tests. Please review, not sure who knows this code best ?
=> Compatibility with Pytest 5.4

CHANGES.rst, pytest_doctestplus/plugin.py
A hacky but more global fix than astropy/astropy#10242 ? 😬
=> No error if import fails unconditionally

CHANGES.rst, README.rst, pytest_doctestplus/plugin.py, pytest_doctestplus/utils.py, tests/test_doctestplus.py
This implements an idea related to those in https://github.com/astropy/pytest-doctestplus/issues/110, namely that we can skip collecting doctests in specific sub-packages by specifying paths and requirements in the ``setup.cfg`` file, e.g.:
```
doctest_subpackage_requires =
astropy/wcs/*:scipy>2.0;numpy>1.14
astropy/cosmology/*:scipy>1.0
```
This ended up being cleaner than using e.g. ``__doctest_subpackage_requires__`` in e.g. ``__init__.py`` files since these would need to be parsed with e.g. ast and not imported and so on.
Note that for skipping ``setup_package.py`` files there is already a solution which is to specify:
```
doctest_norecursedirs =
*/setup_package.py
```
in ``setup.cfg`` files and it works nicely.
Note that this then adds back the default behavior of failing on import …
=> Skip doctest collection in subpackages based on requirements

.travis.yml, README.rst
This will hopefully fix chronic Windows failure. Same patch as the one we applied to `astropy`.
Current error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\tools\\miniconda3\\envs\\test\\Lib\\venv\\scripts\\nt\\python.exe'
```
Also change link to Travis badge.
=> TST: Do not use conda for OSX and Windows

CHANGES.rst, setup.cfg
We use pkg_resources, which is provided by setuptools, in utils.py.
This will resolve issues in those rare cases where you can install
pytest-doctestplus without having setuptools present, such as when
using conda-forge.
Closes #93
=> list setuptools as a runtime dependency

pytest_doctestplus/utils.py, tests/test_utils.py
While removing Python < 3.4 compatibility in 410efdc685551fd4667e9d1a830ff40e7da203e8, I missed that several methods were needed only for Python < 3.4 and are hence no more needed.
For reference, this code was added in d7e81f525597b80897b367d395e5c668c5f8e1b8
I think we could rework this code using [packaging](https://packaging.pypa.io/en/latest/requirements/) and [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), to remove the `pkg_resources` dependency. Maybe later.
=> Remove old code (Python 3.4) in ModuleChecker

CHANGES.rst, README.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
For https://github.com/astropy/astropy/pull/11137
Basically copy/pasted from IGNORE_WARNINGS
=> Add flag to show warnings

README.rst, pytest_doctestplus/sphinx/doctestplus.py
I could see no good reason why this extension was in `sphinx-astropy` rather than `pytest_doctestplus` if all it is doing is telling sphinx to ignore the doctestplus metadata?
I made one small modification to this, which is to set the `override=True` flag on the two directives which are also defined in the sphinx doctest extension, this prevents any warnings being raised when parsing the conf.py file.
=> Add the doctestplus sphinx extension

.github/workflows/publish.yml
Follow up of https://github.com/pypa/twine/pull/715#issuecomment-750851291
With `--strict`, `twine check` will fail if there are warnings, preventing a release until they are fixed.
=> MNT: Use --strict in twine check

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
=> Fix issue with IGNORE_WARNINGS and SHOW_WARNINGS and skipped blocks

CHANGES.rst, pytest_doctestplus/plugin.py
This PR fixes a bug where the handling of `IGNORE_WARNINGS`/`SHOW_WARNINGS` flags in module docstrings is entirely skipped over if `--remote-data=any` is specified (for concurrent use of the `pytest-remotedata` plugin).
=> Fixed logic for IGNORE_WARNINGS/SHOW_WARNINGS for --remote-data=any

.github/workflows/publish.yml, .github/workflows/python-tests.yml
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
=> MNT: Replace master with main

.github/workflows/python-tests.yml, pytest_doctestplus/plugin.py, tox.ini
Ref https://github.com/pytest-dev/pytest/pull/7870
Close  #156
=> Update config._getconftest_pathlist for pytest-dev

.github/workflows/publish.yml, .github/workflows/python-tests.yml, CHANGES.rst, setup.cfg, tox.ini
Small updates while using doctestplus as an example for sphinx-astropy.
=> Setup updates, remove Python 3.6

.gitignore, .vscode/settings.json, CHANGES.rst, README.rst, pytest_doctestplus/plugin.py, setup.cfg, tests/docs/skip_some.rst, tests/docs/skip_some_remote_data.rst, tests/test_doctestplus.py, tox.ini
This is my attempt of resolving the issue of adding directive supporting the use of remote data in doctests. 
The issue can be found here https://github.com/astropy/pytest-doctestplus/issues/2 
EDIT: Fix #2 
EDIT: Re-posted notes from the author below.
* A fourth directive `.. doctest-remote-data::`   that skips the next doctest chunk if `--remote-data` is not passed as an argument to the pytest command is included
* If `--remote-data` option was not passed then check the chunk of strings provided by the result of `doctest.DocTestParser.parse` for the new directives using regex
* If the new directive was matched, then skip the test
=> ENH: Support remote data in doctest

pytest_doctestplus/sphinx/doctestplus.py
This one is required to fix #161 via https://github.com/astropy/sphinx-astropy/pull/45
A changelog entry will be also required, and am happy to tag a new release to get rid of those fires. The only question is that should it be 0.9.1 or a new 0.10.0?
=> Adding the doctest-remote-data directive to sphinx

setup.cfg, tests/Makefile, tests/conf.py, tests/docs/skip_all.rst, tests/docs/skip_some.rst, tests/docs/skip_some_remote_data.rst, tests/index.rst, tests/make.bat, tox.ini
This is to be able to run the simplest `sphinx-build tests tests/_build/html` job to render the docs.
We only need this to be able to check whether the directives indeed work, not to create a narrative docs, so probably a CI job is enough, no need to drag RTD into the picture.
=> Adding basic sphinx config to be able to sphinx-build

README.rst, pytest_doctestplus/sphinx/doctestplus.py, tests/docs/skip_some.rst
=> ENH: Support testcleanup

pytest_doctestplus/sphinx/doctestplus.py, tests/test_doctestplus.py
`distutils` is deprecated. Also remove outdated comment.
=> MNT: Stop using distutils

.github/workflows/python-tests.yml
The windows-latest GitHub Actions virtual environment just switched from windows-2019 to windows-2022. The windows-2022 virtual environment cannot build Python C extensions (see actions/virtual-environments#5141). As a temporary workaround, switch to using windows-2019.
Fixes #177.
=> Use windows-2019 for GitHub Actions jobs

.github/workflows/python-tests.yml
Reverts astropy/pytest-doctestplus#178.
This might be fixed now...
=> Revert "Use windows-2019 for GitHub Actions jobs"

CHANGES.rst, README.rst, pytest_doctestplus/output_checker.py, tests/test_doctestplus.py
Before this PR, floating numbers in arrays are compared as floating numbers, but floating numbers in dicts are not, because they end on "}". This PR simply adds "}" to the regexp that determines what can be at the end of a floating number to allows for doctests like
>>> x = {'a': 1/3., 'b': 2/3.}
>>> x    # doctest: +FLOAT_CMP
{'a': 0.333333, 'b': 0.666666}
which failed before this PR.
=> Allow float comparison in dicts

tests/test_doctestplus.py
[`pytest` provides two fixtures for creating temporary directories](https://docs.pytest.org/en/stable/how-to/tmp_path.html): the recommended `tmp_path`, which uses `pathlib.Path` from the Python standard library, and the legacy `tmpdir`, which uses a third party library. The tests here now use `tmp_path` instead of `tmpdir`.
For the same reason the [`testdir`](https://docs.pytest.org/en/stable/reference/reference.html?highlight=testdir#testdir) fixture should be replaced with [`pytester`](https://docs.pytest.org/en/stable/reference/reference.html?highlight=testdir#pytester), but that would require the minimum supported `pytest` version to be 6.2.
=> Replace `tmpdir` test fixture with `tmp_path`

tests/test_doctestplus.py
One of the tests was skipped with `pytest` versions older than 4.3, but the minimum required `pytest` version is 4.6 since 08060276b4f860fce9b49ce0786fc77cd49ccc09
=> Remove an obsolete version check from tests

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
=> ENH: Report doctests raising skip exceptions as skipped

README.rst
Version check is supported in the `doctest-requires` directive since v0.5 (2019-11-15, #78) but I didn't know until I dug into the change log.
ref: https://github.com/astropy/astropy/pull/14797#discussion_r1189980217
=> DOC: Version check is supported in the doctest-requires directive since v0.5

CHANGES.rst, README.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
Closes #44.
May address #188 at least somewhat.
This may need to be hooked up with an option. Interested in more test cases to check the desired behavior.
cc @bsipocz
=> ENH: Continue running doctests on failure

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
Main motivation is to fix compatibility with pytest 7.4.0.dev though theoretically this plugin should not completely take over the ignore part of test collection? See https://github.com/pytest-dev/pytest/pull/11082#issuecomment-1579954425 for more details. Affected issue:
* https://github.com/astropy/astropy/issues/14930
I am adding a test first to make sure it fails in pytest-dev before trying out the patch. ~I am also using `pytester` instead of `testdir`~, see #200 .
=> MNT: Do not completely take over test collection ignore

.github/workflows/python-tests.yml, LICENSE.rst, setup.cfg, tests/conf.py, tox.ini
This is to close #202 
I'll let CI run, and then will modify one of the devtests to run with python 3.12, which I expect may cause some failures.
Close #208
=> CI: more versions

tests/conftest.py
This gets rid of the testing failure. Whether to have a directive to accept multiple repr ways or not is a separate question and if the answer is yes, that should come in a separate enhancement PR.
=> CI: use numpy printoptions in testing

pytest_doctestplus/plugin.py
To fix #212 (which has more info and reference links)
=> MAINT: fix pytest 8.0dev compatibility

.github/workflows/python-tests.yml
The is no reason to weekend hotfix here.
=> CI: reschedule cron to be on a workday

.github/workflows/python-tests.yml, CHANGES.rst, pytest_doctestplus/plugin.py, setup.cfg, tox.ini
No code changes, except a few very trivial touch-ups. However, there isn't much point develop future enhancements with python 3.7 in mind.
=> MAINT: Remove python3.7 support

setup.cfg
This is stable enough to say that in the metadata, too.
=> DEV: marking the plugin stable

README.rst, tests/test_doctestplus.py
=> Add documentation and unit tests for Markdown code blocks

tests/test_doctestplus.py
In https://github.com/astropy/astropy/pull/15247#issuecomment-1703297888, it was requested that `pytest-doctestplus` add unit testing to confirm the support of `doctest_nocursedirs` and `doctest_subpackage_requires`. This PR adds the requested tests.
~Note that this PR requires bumping the minimum `pytest` version from 4.6 to 6. While this is a big jump it is inline with the [Scientific Python Style Guide](https://learn.scientific-python.org/development/guides/pytest/#configuring-pytest). In particular PP302 says that projects should use `pytest` 6 or later. Moreover, the method to test `pyproject.toml` files for `pytest` configuration, [`makepyprojecttoml`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.Pytester.makepyprojecttoml), was only added in `pytest 6.0.0`.~
I …
=> Add pyproject.toml tests for some options

pytest_doctestplus/output_checker.py
Remove previous workarounds for Python 2 old-style classes.
=> Use super for output checker inheritance

pytest_doctestplus/output_checker.py
CPython source has no __init__ for this class, but just in case, and to
reassure readers.
https://github.com/python/cpython/blob/main/Lib/doctest.py#L1609
=> Precautionary init for OutputChecker

.github/workflows/publish.yml, .github/workflows/python-tests.yml
Python 3.12 is released and checkout is now at v4.
=> TST: Use Python 3.12 stable, bump checkout version

CHANGES.rst, pytest_doctestplus/plugin.py, tests/python/doctests.py
Since the logic was written in a negate way compared to the normal skipping, the module level skip didn't take into account the special "*" and "." patterns.
gh-109 probably misdiagnosed the module actually missing only on the run the had pytest-xdist: the test does not seem to ever pass either way.
Closes gh-109
=> BUG: Fix module level import requires

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
=> Skip __main__.py

CHANGES.rst, pytest_doctestplus/plugin.py
8.1.1 contains the `consider_namespace_packages` that were addressed in https://github.com/scientific-python/pytest-doctestplus/pull/241 However the fix assumed those changes would be in 8.2 instead of 8.1.1.
This PR adjusts the version check to include the fix for 8.1.1
Fixes #243
=> MNT: pytest 8.1.1 compatibility

tests/test_doctestplus.py
This is known to fail on Python 3.11.9 because `--doctest-ufunc` was broken for wrapped ufuncs without docstrings by https://github.com/python/cpython/pull/115440.
=> TST: add tests for ufuncs without docstrings, wrapped or not

.github/workflows/python-tests.yml
`macos-latest` is now arm with no available python 3.8, so we use an explicit name for an older os version. This should fix the currently failing CI
=> CI: use available osx image for old python

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
The code may have more than one line, so need to account for that.
Closes gh-252
=> BUG: Fix multiline code in generate/update diff

tests/test_doctestplus.py
I forgot to delete these lines (the pytest print removes the interesting stuff, so it's hard to see what differs just from them).
=> MAINT: Remove accidental debug print from new tests

CHANGES.rst, pytest_doctestplus/utils.py, setup.cfg
Yesterday we ran into some issues with the latest version of setuptools at astropy (see [this issue](https://github.com/astropy/astropy/issues/16745) for context).
In summary, what happened is that setuptools 71 brought in a couple runtime side effects, resulting in some confusing error messages.
My analysis showed that `setuptools` is only present in the runtime environment that astropy runs tests with because it's brought in by this package, which only requires it for a single line of code, so I refactored it using standard lib `importlib.metadata` + `packagaging` (which is already a runtime dependency here), eliminating `setuptools` as a runtime dependency, which down the road eliminates a source of instabilitly for any package that relies on pytest-doctestplus.
In case it's not clear …
=> DEP: refactored out runtime dependency on setuptools

.github/workflows/python-tests.yml, CHANGES.rst, pytest_doctestplus/plugin.py, tox.ini
I see test failures locally, but there is also a puzzling one for older pythons that I see in my dev environment, but not when I run the tests from tox, so ultimately we may run into some new cross incompatibility with some other plugin.
(This will need a changelog once some actual code changes are needed for incompatibility fixes, but not until all the diff stays within the territory of the tests)
=> MAINT: adding python3.13 to CI and fix any incompatibilities

tests/test_doctestplus.py
This should fix CI and close #265 
Can be merged with a green CI.
=> TST: add one more python release to xfail list

pytest_doctestplus/plugin.py
=> Don't assume config exists.

.github/workflows/publish.yml, .github/workflows/python-tests.yml, CHANGES.rst, pytest_doctestplus/output_checker.py, pytest_doctestplus/plugin.py, setup.cfg, tests/python/doctests.py, tests/test_doctestplus.py, tox.ini
I have some issues locally when running the tests, please don't merge this just yet even if CI is all green, so I can ensure that it's indeed just a local issue (I don't see it with tox, but do see it when running tests directly in the source)
=> MAINT: dropping python3.8 support

.github/workflows/python-tests.yml, CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py, tox.ini
`pytest-asyncio` reads [1] `collector.obj` during test collection which raises an `ImportError` for `DocTestTextfilePlus`. We fix this by aligning that class with pytest’s `DoctestTextfile` [2] and setting `obj` to `None`.
Fixes #256
[1]: https://github.com/pytest-dev/pytest-asyncio/blob/eb63d5ad0ca21041726ada3d5c00211d36418a9b/pytest_asyncio/plugin.py#L640
[2]: https://github.com/pytest-dev/pytest/blob/fc56ae365fcdea800f91683186136a8191e22399/src/_pytest/doctest.py#L421
=> Make compatible with pytest-asyncio

CHANGES.rst, README.rst, pytest_doctestplus/plugin.py, pytest_doctestplus/sphinx/doctestplus.py, tests/test_doctestplus.py
The need for this came up again recently in astroquery, so finally I got down to do it.
To close https://github.com/scientific-python/pytest-doctestplus/issues/183
=> ENH: adding doctest-requires-all directive

CHANGES.rst, pytest_doctestplus/plugin.py, pytest_doctestplus/sphinx/doctestplus.py, tests/docs/skip_some_remote_data.rst, tests/test_doctestplus.py
This should address #146 
EDIT: Fix #146
=> ENH: adding doctest-remote-data-all directive

tests/test_doctestplus.py
This should fix the failing jobs we currently see in cron
=> TST: adding new python version to the fail list

.github/release.yml
This will just make the github release notes nicer
=> MAINT: exclude bots from release notes
