.travis.yml, appveyor.yml, pytest_doctestplus/plugin.py, setup.cfg, tests/docs/skip_all.rst, tests/docs/skip_some.rst, tests/python/doctests.py, tests/python/skip_doctests.py
The unit tests are not completely satisfying, but I'm not sure there's a better way. I should probably take a look at the test suite for the standard doctest plugin.
=> Add unit tests and set up CI

pytest_doctestplus/plugin.py
This fixes #1 and backports astropy/astropy#6605 to this plugin.
=> Add backport bug fix from astropy

CHANGES.rst, pytest_doctestplus/output_checker.py
=> Port fix to floatcmp from astropy core

licenses/README.rst, licenses/SYMPY_LICENSE.rst, pytest_doctestplus/output_checker.py
@astrofrog apologies for the delay.
=> Add sympy license

CHANGES.rst, README.rst, pytest_doctestplus/plugin.py
This fixes #25. See updated README for details.
cc @weaverba137
=> Update behavior of plugin when using --doctest-modules

.travis.yml, CHANGES.rst, appveyor.yml, setup.py
=> Release candidate for v0.2.0

CHANGES.rst, pytest_doctestplus/plugin.py
=> Honor the collect_ignore option used in conftest.py

CHANGES.rst, README.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
This resolves #38. @oscarbenjamin please take a look.
=> Make use of doctest_optionflags settings

.travis.yml, pytest_doctestplus/plugin.py
Not sure how it passed all tests in the previous PR (#61) a few months ago.
=> Fix another importlib deprecation

pytest_doctestplus/plugin.py, tests/python/doctests.py
=> fix __doctest_requires__ with submodules

pytest_doctestplus/output_checker.py, tests/test_doctestplus.py
=> allow to use float comparator and ellipsis at the same time

pytest_doctestplus/plugin.py, setup.cfg, tests/test_doctestplus.py
=> respect ignore and ignore-glob options

tests/test_doctestplus.py
As discussed in astropy/astropy#9629
=> Move test from astropy

setup.cfg
=> Add max line length for flake 8

pytest_doctestplus/plugin.py
=> Fix comment_characters key typo

.travis.yml, pytest_doctestplus/plugin.py, pytest_doctestplus/utils.py
ref and close #119
fix #118 
(edited)
=> Debug failure with pytest-dev

.gitignore, .travis.yml, pyproject.toml, pytest_doctestplus/__init__.py, setup.cfg, setup.py, tox.ini
Updates to the infrastructure to be consistent with other packages
=> Updated package infrastructure to use tox for testing and setuptools_scm

pytest_doctestplus/plugin.py
As recommended in https://github.com/pytest-dev/pytest/pull/8122#issuecomment-745450317
=> MNT: Compat with pytest>=6.3

setup.cfg
=> MNT: Require packaging >= 17.0

.github/workflows/publish.yml
As discussed over at astropy/pytest-astropy-header#35
=> MNT: Minor updates to publish workflow

.github/workflows/python-tests.yml, CHANGES.rst, pytest_doctestplus/plugin.py, setup.cfg, tox.ini
The version check wasn't working for pre-releases.
Fix #170.
=> Compat with Pytest 7.0.0rc1

README.rst
=> DOC: adding doctest-skip-all

.github/workflows/publish.yml
This PR should fix the broken testing in the release action #214
=> CI: fix release action

CHANGES.rst, pytest_doctestplus/plugin.py, tests/test_doctestplus.py
=> Support import-mode

pytest_doctestplus/plugin.py
To close https://github.com/scientific-python/pytest-doctestplus/issues/237
=> MAINT: remove special conftest handling

.github/workflows/python-tests.yml, tox.ini
closes #244
cc: @bsipocz @pllim
=> ci: add testing for `pytest~=8.1`

.github/dependabot.yml
No need for weekly updates from dependabot, monthly is more than enough here.
cc @pllim as you added the original configs.
=> MAINT: No need for weekly dependabot
